src/models/email_subscriptions/views.py
from flask import Blueprint, request, session, render_template, jsonify, app

from src.models.email_subscriptions.email_subscription import EmailSubscription

email_subscription_blueprint = Blueprint('email_subscriptions', __name__)

@email_subscription_blueprint.route('/subscribe/', methods=['POST'])
def subscribe():
    email = request.form['email']
    status = "No Good"
    message = "There was an error adding your email to our subscription list."
    try:
        subscribed = EmailSubscription.new(email)
        if subscribed:
            status = "OK"
            message = "Success! Your email has been added to our subscription list!"
        return jsonify({"status": status, "message": message, "email": email})
    except Exception as e:
        return jsonify({"status": status, "message": str(e)})

src/models/posts/views.py
import math

import src.models.posts.errors as PostErrors
from flask import Blueprint, request, render_template, jsonify, url_for
from src.models.posts.post import Post
import src.models.users.decorators as user_decorators
from werkzeug.utils import redirect
import datetime
import src.models.posts.constants as POST_CONSTANTS

post_blueprint = Blueprint('posts', __name__)


@post_blueprint.route('/', methods=['GET'], defaults={'tag': None})
@post_blueprint.route('/<tag>')
def all(tag):
    if tag is not None:
        posts = list(reversed(list(Post.getManyByTag(tag))))
    else:
        tag = 'all'
        posts = list(reversed(list(Post.getAll())))
    num_pages = math.ceil(len(posts) / POST_CONSTANTS.MAX_RESOURCES_PER_PAGE)
    max_pages_shown = POST_CONSTANTS.MAX_PAGES_SHOWN if num_pages >= POST_CONSTANTS.MAX_PAGES_SHOWN else num_pages
    page = 1
    if 'page' in request.args.keys():
        if int(request.args['page']) <= num_pages:
            page = int(request.args['page'])
        else:
            page = num_pages
    first_index = (page - 1) * POST_CONSTANTS.MAX_RESOURCES_PER_PAGE
    last_index = page * POST_CONSTANTS.MAX_RESOURCES_PER_PAGE
    posts = posts[first_index:last_index]
    tags = list(Post.getAllTags())
    for i in range(len(tags)):
        tags[i] = tags[i]['tag'].capitalize()
    css = [{'prefix': 'css/compiled/', 'name': 'resources'}]
    return render_template('resources.html', posts=posts, tags=tags, css=css, selectedTag=tag, page=page, max_per_page=POST_CONSTANTS.MAX_RESOURCES_PER_PAGE, num_pages=num_pages, max_pages_shown=max_pages_shown)

@post_blueprint.route('/view/<id>', methods=['GET'])
def view(id):
    post = Post.getOneById(id)
    if post:
        css = [{'prefix': 'css/compiled/', 'name': 'resource'}]
        return render_template('resource.html', post=post, css=css)

@post_blueprint.route('/new/', methods=['GET', 'POST'])
@user_decorators.requires_admin_permissions(return_user=False)
def new():
    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        body = request.form['body'].strip()
        tag = request.form['tag']
        videoURL = request.form['videoURL']
        status = "No Good"
        message = "Error: item not inserted"

        if not title or not description or not tag or (not body and not videoURL):
            return {"status": status, "message": message}

        try:
            post_added = Post.new(title, description, body, tag, videoURL)
            if post_added:
                status = "OK"
                message = "Success!!!"
            return jsonify(
                {"status": status, "message": message, "body": body, "tag": tag, "videoURL": videoURL, "timestamp": datetime.datetime.now()})
        except PostErrors.PostError as e:
            return e.message
    else:
        tags = list(Post.getAllTags())
        for i in range(len(tags)):
            tags[i] = tags[i]['tag']
        return render_template('posts/new.html', tags=tags)


@post_blueprint.route('/edit/<id>', methods=['GET', 'POST'])
@user_decorators.requires_admin_permissions(return_user=False)
def update(id):
    post = Post.getOneById(id)
    post['body'] = ','.join(post['body'])
    tags = list(Post.getAllTags())
    for i in range(len(tags)):
        tags[i] = tags[i]['tag']
    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        body = request.form['body']
        tag = request.form['tag']
        videoURL = request.form['videoURL']
        status = "No Good"
        message = "Error: item not inserted"

        if not title or not description or not tag or (not body and not videoURL):
            return {"status": status, "message": message}

        try:
            post_updated = Post.update(id, title, description, body, tag, videoURL)
            if post_updated:
                status = "OK"
                message = "Success!!!"
            return jsonify(
                {"status": status, "message": message, "body": body, "tag": tag, "videoURL": videoURL, "timestamp": datetime.datetime.now()})
        except PostErrors.PostError as e:
            return e.message
    else:
        return render_template('posts/edit.html', post=post, tags=tags)

@post_blueprint.route('/remove/<id>', methods=['GET'])
@user_decorators.requires_admin_permissions(return_user=False)
def delete(id):
    status = "No Good"
    message = "Error: could not delete post"
    try:
        post_deleted = Post.delete(id)
        if post_deleted:
            return redirect(url_for('posts.all'))
        return jsonify({"status": status, "message": message, "timestamp": datetime.datetime.now()})
    except PostErrors.PostError as e:
        return e.message



@post_blueprint.route('/search/', methods=['GET'])
def search():
    input_tag = request.args['input-tag'] if 'input-tag' in request.args else None
    select_tag = request.args['select-tag'] if 'select-tag' in request.args else None
    tag = None
    status = "No Good"
    message = "We're having trouble loading our resources right now! Please try again later."
    try:
        if input_tag is not None:
            tag = input_tag
        elif select_tag is not None:
            tag = select_tag
        if tag is not None and tag != "all":
            tag = tag.lower()
            posts = list(reversed(list(Post.getManyByTag(tag))))
        else:
            posts = list(reversed(list(Post.getAll())))

        num_pages = math.ceil(len(posts) / POST_CONSTANTS.MAX_RESOURCES_PER_PAGE)
        max_pages_shown = POST_CONSTANTS.MAX_PAGES_SHOWN if num_pages >= POST_CONSTANTS.MAX_PAGES_SHOWN else num_pages
        posts = posts[:POST_CONSTANTS.MAX_RESOURCES_PER_PAGE]

        if posts is not None:
            status = "OK"
            message = "Success!!!"
            for post in posts:
                post['_id'] = str(post['_id'])
                post['user_id'] = str(post['user_id'])
        return jsonify({"status": status, "message": message, "posts": posts, "num_pages": num_pages, "max_pages_shown": max_pages_shown})
    except Exception:
        return jsonify({"status": status, "message": message})

@post_blueprint.route('/paginate/', methods=['GET'])
def paginate():
    page = int(request.args['page'])
    tag = request.args['tag']
    status = 'No good'
    message = "We're having trouble loading our resources right now! Please try again later."
    try:
        if tag is not None and tag != "all":
            tag = tag.lower()
            posts = list(reversed(list(Post.getManyByTag(tag))))
        else:
            posts = list(reversed(list(Post.getAll())))

        first_index = (page - 1) * POST_CONSTANTS.MAX_RESOURCES_PER_PAGE
        last_index = page * POST_CONSTANTS.MAX_RESOURCES_PER_PAGE
        posts = posts[first_index:last_index]
        if posts is not None:
            status = "OK"
            message = "Success!!!"
            for post in posts:
                post['_id'] = str(post['_id'])
                post['user_id'] = str(post['user_id'])
        return jsonify({"status": status, "message": message, "posts": posts, "page": page})
    except Exception as e:
        if len(str(e)) != 0:
            message = str(e)
        return jsonify({"status": status, "message": message})



@post_blueprint.route('/tag-editor/', methods=['GET'])
@user_decorators.requires_admin_permissions(return_user=False)
def tagEditor():
    tags = list(Post.getAllTags())
    for i in range(len(tags)):
        tags[i] = tags[i]['tag']
    css = [{'prefix': 'css/compiled/', 'name': 'tag-editor'}]
    return render_template('posts/tag-editor.html', tags=tags, css=css)

@post_blueprint.route('/add-tag/', methods=['GET', 'POST'])
@user_decorators.requires_admin_permissions(return_user=False)
def addTag():
    if request.method == 'POST':
        tag = request.form['tag'].lower()
        status = "No Good"
        message = "Error: tag not inserted"

        if not tag:
            return {"status": status, "message": message}

        try:
            tag_added = Post.addTag(tag)
            if tag_added:
                status = "OK"
                message = "Success!!!"
            return jsonify(
                {"status": status, "message": message, "tag": tag, "timestamp": datetime.datetime.now()})
        except PostErrors.PostError as e:
            return e.message
    else:
        return render_template('posts/add-tag.html')

@post_blueprint.route('/remove-tag/', methods=['POST'])
@user_decorators.requires_admin_permissions(return_user=False)
def deleteTag():
    status = "No Good"
    message = "Error: could not delete post"
    tag = request.form['tag']
    try:
        tag_deleted = Post.deleteTag(tag)
        if tag_deleted:
            status = 'OK'
            message = 'Sucess!!!'
        return jsonify({"status": status, "message": message, "timestamp": datetime.datetime.now()})
    except PostErrors.PostError as e:
        return e.message

src/models/users/views.py
import src.models.users.errors as UserErrors
from flask import Blueprint, request, session, render_template, jsonify, app
from src.models.users.user import User
from src.models.posts.post import Post
import src.models.users.decorators as user_decorators
from werkzeug.utils import redirect
from src.app import app
from src.utils import Utils

user_blueprint = Blueprint('users', __name__)

@user_blueprint.route('/register/', methods=['GET'])
def register():
    return render_template('users/register.html')

@user_blueprint.route('/login/', methods=['GET'])
def login():
    return render_template('users/login.html')

@user_blueprint.route('/profile/', methods=['GET'])
@user_decorators.requires_login(return_user=True)
def profile(user):
    user_id = user['_id']
    email = session['email']
    posts = reversed(list(Post.getAllByUserId(user_id)))
    # posts = reversed(list(Post.getAll()))
    tags = list(Post.getAllTags())
    for i in range(len(tags)):
        tags[i] = tags[i]['tag']
    return render_template('users/profile.html', email=email, posts=posts, tags=tags)

@user_blueprint.route('/auth/login', methods=['POST'])
def loginUser():
    email = request.form['email']
    password = request.form['password']
    status = "No Good"
    message = "Error - information provided does not match any account"

    if not email or not password:
        return 'Email and password are required to register'

    if not Utils.email_is_valid(email):
        return 'Email format is not valid'

    if len(password) < 6:
        return 'Password must be at least 8 characters'

    if email not in app.config['ADMINS']:
        return 'This email does not have admin priviliges'

    try:
        valid = User.isLoginValid(email, password)
        if valid:
            session['email'] = email
            status = "OK"
            message = "Success! You have been logged in!"
        else:
            session['email'] = None
        return jsonify({"status": status, "message": message, "email": email})
    except UserErrors.UserError as e:
        return e.message

@user_blueprint.route('/auth/register', methods=['POST'])
def registerUser():
    email = request.form['email']
    password = request.form['password']
    status = "No Good"
    message = "An account with that email already exists"

    if not email or not password:
        return 'Email and password are required to register'

    if not Utils.email_is_valid(email):
        return 'Email format is not valid'

    if len(password) < 6:
        return 'Password must be at least 8 characters'

    if email not in app.config['ADMINS']:
        return 'This email does not have admin priviliges'

    try:
        registered = User.register(email, password)
        if registered:
            status = "OK"
            message = "Success! Your account has been registered!"

        return jsonify({"status": status, "message": message, "email": email})
    except UserErrors.UserError as e:
        return e.message


@user_blueprint.route('/auth/logout', methods=['GET'])
@user_decorators.requires_login()
def logoutUser():
    try:
        status = "No Good"
        User.logout()
        if session['email'] is None:
            return redirect('/')
        return jsonify({"status": status})
    except UserErrors.UserError as e:
        return e.message

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}"/>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <script src="{{ url_for('static', filename='js/jquery-3.4.1.min.js') }}"></script>
    {% for file in css %}
        <link rel="stylesheet" href="{{ url_for('static', filename=file.prefix+file.name+'.css') }}"/>
    {% endfor %}
</head>
<body>
{% include 'header.html' %}
{% block content %}

{% endblock %}
{% include 'footer.html' %}
{% include 'special.html' %}


<script src="{{ url_for('static', filename='js/slick/slick.min.js') }}"></script>
<!--<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>-->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>-->
<!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>-->
</body>
</html>

src/templates/footer.html
{% block content %}
<div class="footer">
    <p>Copyright © 2018 The Holistic Approach to Wellness - All Rights Reserved.</p>
</div>
{% endblock %}

src/templates/header.html
<div class="header">
    <h1 class="logo"><a href="{{ url_for('home') }}">Body By Science</a></h1>
    <ul class="nav">
        <li><a href="{{ url_for('home') }}">Home</a></li>
        <li><a href="{{ url_for('posts.all') }}">Resources</a></li>
        <li><a href="{{ url_for('about') }}">About Us</a></li>
        <li><a href="{{ url_for('contact') }}">Contact</a></li>
        {% if session['email'] %}
            <li class="dropdown-toggle">
                <div class="text">Admin</div>
                <ul class="dropdown-content hidden">
                    {% if isAdmin %}
                        <li><a href="{{ url_for('posts.new') }}">Create post</a></li>
                        <li><a href="{{ url_for('posts.tagEditor') }}">Manage Tags</a></li>
                    {% endif %}
                    <li><a href="{{ url_for('users.logoutUser') }}">Log out</a></li>
                </ul>
            </li>
        {% endif %}
    </ul>
</div>

<script>
    $('.dropdown-toggle .text').on('click', function(e) {
        e.stopPropagation();
        var el = $(this).parent().find('.dropdown-content');
        if (el.hasClass('hidden')) {
            el.removeClass('hidden');
        } else {
            el.addClass('hidden');
        }
    });
    $(document).click(function() {
        if(!$(event.target).closest('.dropdown-content').length) {
            $(".dropdown-content").addClass('hidden');
        }
	});
</script>

src/templates/resource.html
{% extends "base.html" %}
{% block content %}

<div class="resource-page">
    <div class="resource">
        <h1>{{ post['title'] }}</h1>
        {% if post['videoURL'] %}
            <div class="video">
                {{ post['videoURL']|safe }}
            </div>
        {% endif %}
        {% if post['body'] %}
            {% for i in range(len(post['body'])) %}
                <div class="paragraph {{ 'even' if i % 2 == 0 else 'odd'}} ">{{ post['body'][i].replace(';', ',') }}</div>
            {% endfor %}
        {% endif %}
    </div>
    {% if isAdmin %}
        <a href="{{ url_for('posts.update', id=post['_id']) }}"><button class="btn btn-success update disabled">Edit</button></a>
        <a href="{{ url_for('posts.delete', id=post['_id']) }}"><button class="btn btn-success update disabled">Delete</button></a>
    {% endif %}
</div>

{% endblock %}

src/templates/resources.html
{% extends "base.html" %}
{% block content %}

<div class="resources">
    <div class="page-form">
        <div class="container">
            <div class="filter-header">Topics:</div>
            <div class="filters">
                <div class="filter all{{ ' selected' if selectedTag == 'all' else '' }}" data-value="all">
                    <div class="checkmark"></div>
                    <span>All</span>
                </div>
                {% for tag in tags %}
                    <div class="filter{{ ' selected' if tag.lower() == selectedTag else '' }}" data-value="{{ tag }}">
                        <div class="checkmark"></div>
                        <span>{{ tag }}</span>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="posts-container">
        <h4 class="error hidden"></h4>
        <div class="overlay hidden"></div>
        <div class="container">
            <div class="posts-header">
                <h1>{{"Browse our Professionally Curated Resources" if num_pages > 0 else "We don't have any resources for this category right now! Please try another."}}</h1>
            </div>
            <div class="posts">
            {% for post in posts %}
                <div class="post">
                    <a href="{{ url_for('posts.view', id=post['_id']) }}">
                        <div class="content">
                            <div class="top">
                                <div class="title"><h4>{{ post['title'] }}</h4></div>
                            </div>
                            <div class="bottom">
                                <div class="description">{{ post['description'] }}</div>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
            </div>
            <div class="pagination">
                {% if num_pages > 1 %}
                <a class="page prev{{ ' disabled' if page == 1 else ''}}">Prev</a>
                {% for pageNumber in range(1, max_pages_shown + 1) %}
                <a class="page{{ ' active disabled' if pageNumber == page else '' }}" data-page="{{ pageNumber }}">{{ pageNumber }}</a>
                {% endfor %}
                <a class="page next{{ ' disabled' if len(posts) < max_per_page or page == num_pages else '' }}" data-page="2">Next</a>
                {% endif %}
            </div>
        </div>
    </div>

</div>


<script type="text/javascript">
    var renderPosts = function(posts) {
        $('.posts').empty();
        var postDiv;
        var content;
        var top;
        var title;
        var bottom;
        var description;
        var contentContainer;
        posts.forEach((post) => {
            postDiv = $('<div>').addClass('post');
            contentContainer = $('<a>').attr('href', '/resources/'+post['_id'])
            content = $('<div>').addClass('content');
            top = $('<div>').addClass('top');
            title = $('<div>').addClass('title').html('<h4>'+post['title']+'</h4>');
            bottom = $('<div>').addClass('bottom');
            description = $('<div>').addClass('description').html(post['description']);
            top.appendTo(content);
            title.appendTo(top);
            bottom.appendTo(content);
            description.appendTo(bottom);
            content.appendTo(contentContainer);
            contentContainer.appendTo(postDiv);
            postDiv.appendTo($('.posts'));
        });
    }

    var renderPagination = function(page, num_pages, max_pages_shown) {
        $('.pagination').empty();
        var prev;
        var button;
        var next;
        var minPage = 1;
        var maxPage;
        if (num_pages <= 1) {
            return;
        } else if (num_pages <= max_pages_shown) {
            maxPage = num_pages
        } else if (page < Math.ceil(max_pages_shown / 2)) {
            maxPage = max_pages_shown;
        } else if (page <= num_pages - 2) {
            minPage = page - Math.floor(max_pages_shown / 2);
            maxPage = page + Math.floor(max_pages_shown / 2);
        } else {
            minPage = num_pages - (max_pages_shown - 1);
            maxPage = num_pages;
        }

        prev = $('<a>').addClass('page prev').attr('data-page', page - 1).text('Prev');
        if (page === 1) prev.addClass('disabled');
        prev.appendTo($('.pagination'));
        for (let i = minPage; i <= maxPage; i++) {
            button = $('<a>').addClass('page').attr('data-page', i).text(i);
            if (i === page) button.addClass('active disabled');
            button.appendTo($('.pagination'));
        }
        next = $('<a>').addClass('page next').attr('data-page', page + 1).text('Next');
        if (page === num_pages) next.addClass('disabled');
        next.appendTo($('.pagination'));
    }

    $(document).ready(function() {
        let page = {{ page }};
        let num_pages = {{ num_pages }};
        let max_per_page = {{ max_per_page }};
        let max_pages_shown = {{ max_pages_shown }};

        $(window).on("popstate", function (e) {
            location.reload();
        });

        $(document.body).on('click', '.page', function(e) {
            e.preventDefault();
            let self = $(this);
            let nextPage = self.data('page');
            let tag = $('.filter.selected').data('value');
            $.ajax({
                url: '{{ url_for('posts.paginate') }}',
                data: "page="+nextPage+"&tag="+tag,
                type: 'GET',
                beforeSend: function() {
                    $('.overlay').removeClass('hidden');
                },
                success: function(response) {
                    if (response.status === 'OK') {
                        renderPosts(response.posts);
                        window.scrollTo(0, 0);
                        $('.posts-header').addClass('hidden');
                        renderPagination(nextPage, num_pages, max_pages_shown);
                        page = nextPage
                        window.history.pushState(null, null, window.location.pathname + '?page='+page);
                    } else {
                        $('.error').removeClass('hidden');
                        $('.error').text(response.message);
                    }
                },
                error: function(error) {
                    $('.error').removeClass('hidden');
                    $('.error').text(error);
                },
                complete: function() {
                    $('.overlay').addClass('hidden');
                }
            });
        });

        $('button').click(function(e) {
            e.preventDefault();
            $('.error').addClass('hidden');
            $('.error').text('');
            $('select').val('0');
            if($('input').val()) {
                $.ajax({
                    url: '{{ url_for('posts.search') }}',
                    data: "input-tag="+$('input').val(),
                    type: 'GET',
                    beforeSend: function() {
                        $('.overlay').removeClass('hidden');
                    },
                    success: function(response) {
                        if (response.status === 'OK') {
                            renderPosts(response.posts);
                            window.scrollTo(0, 0);
                            $('.posts-header').addClass('hidden');
                        } else {
                            $('.error').removeClass('hidden');
                            $('.error').text('Could not complete search');
                        }
                    },
                    error: function(error) {
                        $('.error').removeClass('hidden');
                        $('.error').text(error);
                    },
                    complete: function() {
                        $('.overlay').addClass('hidden');
                    }
                });
            } else if ($('select').val() === "0") {
                $('.error').removeClass('hidden');
                $('.error').text('Error: no tag selected');
            }

        });

        $('.filter').on('click', function(e) {
            e.preventDefault();
            $('.error').addClass('hidden');
            $('.error').text('');
            var el = $(this);
            if (el.data('value')) {
                $('.filter').removeClass('selected');
                $.ajax({
                    url: '{{ url_for('posts.search') }}',
                    data: "select-tag="+el.data('value'),
                    type: 'GET',
                    beforeSend: function() {
                        $('.overlay').removeClass('hidden');
                    },
                    success: function(response) {
                        if (response.status === 'OK') {
                            el.addClass('selected');
                            window.scrollTo(0, 0);
                            renderPosts(response.posts);
                            $('.btn.prev').addClass('disabled');
                            page = 1;
                            if (response.posts.length === 0) {
                                $('.posts-header').removeClass('hidden');
                                $('.posts-header h1').text("We don't have any resources for this category right now! Please try another.");
                            } else {
                                $('.posts-header').addClass('hidden');
                                if (response.posts.length < max_per_page) {
                                    $('.btn.next').addClass('disabled');
                                } else {
                                    $('.btn.next').removeClass('disabled');
                                }
                            }

                            num_pages = response.num_pages;
                            max_pages_shown = response.max_pages_shown;
                            renderPagination(page, num_pages, max_pages_shown);
                            let tag = el.data('value') !== 'all' ? el.data('value').toLowerCase() : ''
                            window.history.pushState(null, null, '/resources/' + tag);

                        } else {
                            $('.error').removeClass('hidden');
                            $('.error').text(response.message);
                        }
                    },
                    error: function(error) {
                        $('.error').removeClass('hidden');
                        $('.error').text("We're having trouble loading our resources right now! Please try again later.");
                    },
                    complete: function() {
                        $('.overlay').addClass('hidden');
                    }
                });
            } else if (!$(this).data('value')) {
                $('.error').removeClass('hidden');
                $('.error').text("We're having trouble loading our resources right now! Please try again later.");
            }
        });
    });
</script>
{% endblock %}

src/templates/special.html
<div class="special">
    I SEE YOU MINKY!!!!
</div>
<script>
    $(document).ready(function(){
        var secret = '38384040373937396665';
        var input = "";
        var timer;

        $(document).keyup(function(e) {
            input += e.which;
            clearTimeout(timer);
            timer = setTimeout(function() { input = ""; }, 1000);
            check_input();
        });

        function check_input() {
            if(input == secret) {
                console.log('equal');
                $('.special').addClass('visible');
            }
        };
    });
</script>