src/models/posts/views.py
import math

import src.models.posts.errors as PostErrors
from flask import Blueprint, request, render_template, jsonify, url_for
from src.models.posts.post import Post
import src.models.users.decorators as user_decorators
from werkzeug.utils import redirect
import datetime
import src.models.posts.constants as POST_CONSTANTS

post_blueprint = Blueprint('posts', __name__)


@post_blueprint.route('/', methods=['GET'], defaults={'tag': None})
@post_blueprint.route('/<tag>')
def all(tag):
    if tag is not None:
        posts = list(reversed(list(Post.getManyByTag(tag))))
    else:
        tag = 'all'
        posts = list(reversed(list(Post.getAll())))
    num_pages = math.ceil(len(posts) / POST_CONSTANTS.MAX_RESOURCES_PER_PAGE)
    max_pages_shown = POST_CONSTANTS.MAX_PAGES_SHOWN if num_pages >= POST_CONSTANTS.MAX_PAGES_SHOWN else num_pages
    page = 1
    if 'page' in request.args.keys():
        if int(request.args['page']) <= num_pages:
            page = int(request.args['page'])
        else:
            page = num_pages
    first_index = (page - 1) * POST_CONSTANTS.MAX_RESOURCES_PER_PAGE
    last_index = page * POST_CONSTANTS.MAX_RESOURCES_PER_PAGE
    posts = posts[first_index:last_index]
    tags = list(Post.getAllTags())
    for i in range(len(tags)):
        tags[i] = tags[i]['tag'].capitalize()
    css = [{'prefix': 'css/compiled/', 'name': 'resources'}]
    return render_template('resources.html', posts=posts, tags=tags, css=css, selectedTag=tag, page=page, max_per_page=POST_CONSTANTS.MAX_RESOURCES_PER_PAGE, num_pages=num_pages, max_pages_shown=max_pages_shown)

@post_blueprint.route('/view/<id>', methods=['GET'])
def view(id):
    post = Post.getOneById(id)
    if post:
        css = [{'prefix': 'css/compiled/', 'name': 'resource'}]
        return render_template('resource.html', post=post, css=css)

@post_blueprint.route('/new/', methods=['GET', 'POST'])
@user_decorators.requires_admin_permissions(return_user=False)
def new():
    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        body = request.form['body'].strip()
        tag = request.form['tag']
        videoURL = request.form['videoURL']
        status = "No Good"
        message = "Error: item not inserted"

        if not title or not description or not tag or (not body and not videoURL):
            return {"status": status, "message": message}

        try:
            post_added = Post.new(title, description, body, tag, videoURL)
            if post_added:
                status = "OK"
                message = "Success!!!"
            return jsonify(
                {"status": status, "message": message, "body": body, "tag": tag, "videoURL": videoURL, "timestamp": datetime.datetime.now()})
        except PostErrors.PostError as e:
            return e.message
    else:
        tags = list(Post.getAllTags())
        for i in range(len(tags)):
            tags[i] = tags[i]['tag']
        return render_template('posts/new.html', tags=tags)


@post_blueprint.route('/edit/<id>', methods=['GET', 'POST'])
@user_decorators.requires_admin_permissions(return_user=False)
def update(id):
    post = Post.getOneById(id)
    post['body'] = ','.join(post['body'])
    tags = list(Post.getAllTags())
    for i in range(len(tags)):
        tags[i] = tags[i]['tag']
    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        body = request.form['body']
        tag = request.form['tag']
        videoURL = request.form['videoURL']
        status = "No Good"
        message = "Error: item not inserted"

        if not title or not description or not tag or (not body and not videoURL):
            return {"status": status, "message": message}

        try:
            post_updated = Post.update(id, title, description, body, tag, videoURL)
            if post_updated:
                status = "OK"
                message = "Success!!!"
            return jsonify(
                {"status": status, "message": message, "body": body, "tag": tag, "videoURL": videoURL, "timestamp": datetime.datetime.now()})
        except PostErrors.PostError as e:
            return e.message
    else:
        return render_template('posts/edit.html', post=post, tags=tags)

@post_blueprint.route('/remove/<id>', methods=['GET'])
@user_decorators.requires_admin_permissions(return_user=False)
def delete(id):
    status = "No Good"
    message = "Error: could not delete post"
    try:
        post_deleted = Post.delete(id)
        if post_deleted:
            return redirect(url_for('posts.all'))
        return jsonify({"status": status, "message": message, "timestamp": datetime.datetime.now()})
    except PostErrors.PostError as e:
        return e.message



@post_blueprint.route('/search/', methods=['GET'])
def search():
    input_tag = request.args['input-tag'] if 'input-tag' in request.args else None
    select_tag = request.args['select-tag'] if 'select-tag' in request.args else None
    tag = None
    status = "No Good"
    message = "We're having trouble loading our resources right now! Please try again later."
    try:
        if input_tag is not None:
            tag = input_tag
        elif select_tag is not None:
            tag = select_tag
        if tag is not None and tag != "all":
            tag = tag.lower()
            posts = list(reversed(list(Post.getManyByTag(tag))))
        else:
            posts = list(reversed(list(Post.getAll())))

        num_pages = math.ceil(len(posts) / POST_CONSTANTS.MAX_RESOURCES_PER_PAGE)
        max_pages_shown = POST_CONSTANTS.MAX_PAGES_SHOWN if num_pages >= POST_CONSTANTS.MAX_PAGES_SHOWN else num_pages
        posts = posts[:POST_CONSTANTS.MAX_RESOURCES_PER_PAGE]

        if posts is not None:
            status = "OK"
            message = "Success!!!"
            for post in posts:
                post['_id'] = str(post['_id'])
                post['user_id'] = str(post['user_id'])
        return jsonify({"status": status, "message": message, "posts": posts, "num_pages": num_pages, "max_pages_shown": max_pages_shown})
    except Exception:
        return jsonify({"status": status, "message": message})

@post_blueprint.route('/paginate/', methods=['GET'])
def paginate():
    page = int(request.args['page'])
    tag = request.args['tag']
    status = 'No good'
    message = "We're having trouble loading our resources right now! Please try again later."
    try:
        if tag is not None and tag != "all":
            tag = tag.lower()
            posts = list(reversed(list(Post.getManyByTag(tag))))
        else:
            posts = list(reversed(list(Post.getAll())))

        first_index = (page - 1) * POST_CONSTANTS.MAX_RESOURCES_PER_PAGE
        last_index = page * POST_CONSTANTS.MAX_RESOURCES_PER_PAGE
        posts = posts[first_index:last_index]
        if posts is not None:
            status = "OK"
            message = "Success!!!"
            for post in posts:
                post['_id'] = str(post['_id'])
                post['user_id'] = str(post['user_id'])
        return jsonify({"status": status, "message": message, "posts": posts, "page": page})
    except Exception as e:
        if len(str(e)) != 0:
            message = str(e)
        return jsonify({"status": status, "message": message})



@post_blueprint.route('/tag-editor/', methods=['GET'])
@user_decorators.requires_admin_permissions(return_user=False)
def tagEditor():
    tags = list(Post.getAllTags())
    for i in range(len(tags)):
        tags[i] = tags[i]['tag']
    css = [{'prefix': 'css/compiled/', 'name': 'tag-editor'}]
    return render_template('posts/tag-editor.html', tags=tags, css=css)

@post_blueprint.route('/add-tag/', methods=['GET', 'POST'])
@user_decorators.requires_admin_permissions(return_user=False)
def addTag():
    if request.method == 'POST':
        tag = request.form['tag'].lower()
        status = "No Good"
        message = "Error: tag not inserted"

        if not tag:
            return {"status": status, "message": message}

        try:
            tag_added = Post.addTag(tag)
            if tag_added:
                status = "OK"
                message = "Success!!!"
            return jsonify(
                {"status": status, "message": message, "tag": tag, "timestamp": datetime.datetime.now()})
        except PostErrors.PostError as e:
            return e.message
    else:
        return render_template('posts/add-tag.html')

@post_blueprint.route('/remove-tag/', methods=['POST'])
@user_decorators.requires_admin_permissions(return_user=False)
def deleteTag():
    status = "No Good"
    message = "Error: could not delete post"
    tag = request.form['tag']
    try:
        tag_deleted = Post.deleteTag(tag)
        if tag_deleted:
            status = 'OK'
            message = 'Sucess!!!'
        return jsonify({"status": status, "message": message, "timestamp": datetime.datetime.now()})
    except PostErrors.PostError as e:
        return e.message

src/models/users/views.py
import src.models.users.errors as UserErrors
from flask import Blueprint, request, session, render_template, jsonify, app
from src.models.users.user import User
from src.models.posts.post import Post
import src.models.users.decorators as user_decorators
from werkzeug.utils import redirect
from src.app import app
from src.utils import Utils

user_blueprint = Blueprint('users', __name__)

@user_blueprint.route('/register/', methods=['GET'])
def register():
    return render_template('users/register.html')

@user_blueprint.route('/login/', methods=['GET'])
def login():
    return render_template('users/login.html')

@user_blueprint.route('/profile/', methods=['GET'])
@user_decorators.requires_login(return_user=True)
def profile(user):
    user_id = user['_id']
    email = session['email']
    posts = reversed(list(Post.getAllByUserId(user_id)))
    # posts = reversed(list(Post.getAll()))
    tags = list(Post.getAllTags())
    for i in range(len(tags)):
        tags[i] = tags[i]['tag']
    return render_template('users/profile.html', email=email, posts=posts, tags=tags)

@user_blueprint.route('/auth/login', methods=['POST'])
def loginUser():
    email = request.form['email']
    password = request.form['password']
    status = "No Good"
    message = "Error - information provided does not match any account"

    if not email or not password:
        return 'Email and password are required to register'

    if not Utils.email_is_valid(email):
        return 'Email format is not valid'

    if len(password) < 6:
        return 'Password must be at least 8 characters'

    if email not in app.config['ADMINS']:
        return 'This email does not have admin priviliges'

    try:
        valid = User.isLoginValid(email, password)
        if valid:
            session['email'] = email
            status = "OK"
            message = "Success! You have been logged in!"
        else:
            session['email'] = None
        return jsonify({"status": status, "message": message, "email": email})
    except UserErrors.UserError as e:
        return e.message

@user_blueprint.route('/auth/register', methods=['POST'])
def registerUser():
    email = request.form['email']
    password = request.form['password']
    status = "No Good"
    message = "An account with that email already exists"

    if not email or not password:
        return 'Email and password are required to register'

    if not Utils.email_is_valid(email):
        return 'Email format is not valid'

    if len(password) < 6:
        return 'Password must be at least 8 characters'

    if email not in app.config['ADMINS']:
        return 'This email does not have admin priviliges'

    try:
        registered = User.register(email, password)
        if registered:
            status = "OK"
            message = "Success! Your account has been registered!"

        return jsonify({"status": status, "message": message, "email": email})
    except UserErrors.UserError as e:
        return e.message


@user_blueprint.route('/auth/logout', methods=['GET'])
@user_decorators.requires_login()
def logoutUser():
    try:
        status = "No Good"
        User.logout()
        if session['email'] is None:
            return redirect('/')
        return jsonify({"status": status})
    except UserErrors.UserError as e:
        return e.message

src/templates/users/login.html
{% extends "base.html" %}
{% block content %}
<div class="login">
    <h4 class="error hidden"></h4>
    <h1>Log in</h1>
    <div class="container page-form">
        <div class="overlay hidden"></div>
        {% if not session['email'] %}
            <form id="login-form">
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="text" id="email" class="form-control" name="email">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" id="password" class="form-control" name="password">
                </div>
                <button type="submit" class="btn btn-success">Log in</button>
            </form>
        {% else %}
            <h1>You're already logged in!</h1>
            <a href="{{ url_for('users.logoutUser') }}">Log out</a>
        {% endif %}
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        function validate() {
            let isValid = true;
            if ($('#email').val() === '' || $('#password').val() === '') {
                isValid = false;
                $('.error').text("Please fill out all fields before submitting.");
                $('.error').removeClass('hidden');
            } else if (!(/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w+)+$/.test($('#email').val()))) {
                isValid = false;
                $('.error').text("Please enter a valid email address.");
                $('.error').removeClass('hidden');
            } else if ($('#password').val().length < 6) {
                isValid = false;
                $('.error').text("Password must be at least 8 characters");
                $('.error').removeClass('hidden');
            }
            return isValid;
        }

        $('button').click(function(e) {
            e.preventDefault();
            $('.error').addClass('hidden');
            $('.error').text('');
            let valid = validate();
            if (valid) {
                $.ajax({
                    url: '{{ url_for("users.loginUser") }}',
                    data: $('form').serialize(),
                    type: 'POST',
                    beforeSend: function() {
                        $('.overlay').removeClass('hidden');
                    },
                    success: function(response) {
                        if (response.status === 'OK') {
                            window.location.href = "{{ url_for('home') }}";
                        } else {
                            $('.error').removeClass('hidden');
                            $('.error').text('Could not log in');
                        }
                    },
                    error: function(error) {
                        $('.error').removeClass('hidden');
                        $('.error').text(error);
                    },
                    complete: function() {
                        $('.overlay').addClass('hidden');
                    }
                });
            }
        });
    });
</script>
{% endblock %}

src/templates/users/profile.html
{% extends "base.html" %}
{% block content %}
    {% if email %}
        <h1>hello {{ email }}</h1>
        <h4 class="error hidden"></h4>
        <div class="page-form">
            <div class="overlay hidden"></div>
            <form id="search-posts">
                <div class="form-group">
                    <label for="input-tag">Search</label>
                    <input type="text" id="input-tag" class="form-control" name="input-tag">
                </div>
                <div class="form-group">
                    <label for="select-tag">Search by tag</label>
                    <select id="select-tag" class="form-control" name="select-tag">
                        <option value="0"></option>
                        {% for tag in tags %}
                            <option value="{{ tag }}">{{ tag }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit" class="btn btn-success">Search</button>
            </form>
        </div>
        <div class="posts">
            {% for post in posts %}
                <div class="post">
                    <h4>{{ post['body'] }}</h4>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h1>You need to have an account to view this page!</h1>
        <a href="{{ url_for('users.register') }}">Sign up</a>
        <a href="{{ url_for('users.login') }}">Log in</a>
    {% endif %}

<script type="text/javascript">
    var renderPosts = function(posts) {
        $('.posts').empty();
        var post;
        posts.forEach((post) => {
            post = $('<div>').addClass('post').html('<h4>'+post['body']+'</h4>');
            post.appendTo($('.posts'));
        });
    }

    $(document).ready(function() {
        $('button').click(function(e) {
            e.preventDefault();
            $('.error').addClass('hidden');
            $('.error').text('');
            $('select').val('0');
            if($('input').val()) {
                $.ajax({
                    url: '{{ url_for('posts.search') }}',
                    data: "input-tag="+$('input').val(),
                    type: 'POST',
                    beforeSend: function() {
                        $('.overlay').removeClass('hidden');
                    },
                    success: function(response) {
                        if (response.status === 'OK') {
                            console.log(response);
                            renderPosts(response.posts);
                        } else {
                            $('.error').removeClass('hidden');
                            $('.error').text('Could not create post');
                        }
                    },
                    error: function(error) {
                        $('.error').removeClass('hidden');
                        $('.error').text(error);
                    },
                    complete: function() {
                        $('.overlay').addClass('hidden');
                    }
                });
            } else if ($('select').val() === "0") {
                $('.error').removeClass('hidden');
                $('.error').text('Error: no tag selected');
            }

        });

        $('select').on('change', function(e) {
            e.preventDefault();
            $('.error').addClass('hidden');
            $('.error').text('');
            if ($(this).val()) {
                $('input').val('');
                $.ajax({
                    url: '{{ url_for('posts.search') }}',
                    data: "select-tag="+$('select').val(),
                    type: 'POST',
                    beforeSend: function() {
                        $('.overlay').removeClass('hidden');
                    },
                    success: function(response) {
                        if (response.status === 'OK') {
                            console.log(response);
                            renderPosts(response.posts);
                        } else {
                            $('.error').removeClass('hidden');
                            $('.error').text('Could not create post');
                        }
                    },
                    error: function(error) {
                        $('.error').removeClass('hidden');
                        $('.error').text(error);
                    },
                    complete: function() {
                        $('.overlay').addClass('hidden');
                    }
                });
            } else if ($('input').val() === "") {
                $('.error').removeClass('hidden');
                $('.error').text('Error: no tag selected');
            }
        });
    });
</script>
{% endblock %}

src/templates/users/register.html
{% extends "base.html" %}
{% block content %}
<div class="register">
    <h4 class="error hidden"></h4>
    <div class="container page-form">
        <div class="overlay hidden"></div>
        {% if not session['email'] %}
            <form id="register-form">
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="text" id="email" class="form-control" name="email">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" id="password" class="form-control" name="password">
                </div>
                <button type="submit" class="btn btn-success">Sign up</button>
            </form>
        {% else %}
            <h1>You're already logged in!</h1>
            <a href="{{ url_for('users.logoutUser') }}">Log out</a>
        {% endif %}
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        function validate() {
            let isValid = true;
            if ($('#email').val() === '' || $('#password').val() === '') {
                isValid = false;
                $('.error').text("Please fill out all fields before submitting.");
                $('.error').removeClass('hidden');
            } else if (!(/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w+)+$/.test($('#email').val()))) {
                isValid = false;
                $('.error').text("Please enter a valid email address.");
                $('.error').removeClass('hidden');
            } else if ($('#password').val().length < 6) {
                isValid = false;
                $('.error').text("Password must be at least 8 characters");
                $('.error').removeClass('hidden');
            }
            return isValid;
        }

        $('button').click(function(e) {
            e.preventDefault();
            $('.error').addClass('hidden');
            $('.error').text('');
            let valid = validate();
            if (valid) {
                $.ajax({
                    url: '{{ url_for('users.registerUser') }}',
                    data: $('form').serialize(),
                    type: 'POST',
                    beforeSend: function() {
                        $('.overlay').removeClass('hidden');
                    },
                    success: function(response) {
                        if (response.status === 'OK') {
                            window.location.href = "{{ url_for('home') }}";
                        } else {
                            $('.error').removeClass('hidden');
                            $('.error').text('Could not register user.');
                        }
                    },
                    error: function(error) {
                        $('.error').removeClass('hidden');
                        $('.error').text(error);
                    },
                    complete: function() {
                        $('.overlay').addClass('hidden');
                    }
                });
            }
        });
    });
</script>
{% endblock %}